### ISSUE TITLE
Sign operation failed

### ISSUE THREAD

**Issue by qiluge** [goat-systems/go-tezos#136]
reference this code:
```
func TestRevealOperation(t *testing.T) {
	TestNewTezosSdk(t)
	pkh := "tz1buwfQ3j7gTSM5QU8bmG2YnfH8zEnsjm92"
	pubKey := "edpkvJ4LqnbAVXoK12Q1HFuP42UTWcfJtixgKVimCEeStCZwi91x9B"
	wallet, err := gotezos.ImportWallet(pkh, pubKey,
		"edskRhT17Wmv2gbRG8fh66kCM3pQ3xeNuv7Bn5vKJdEVJAoDiEdVf6zok1EPXrDEmDjxtGEGcCQaTs13vstjmjjKDw7A5twsCh")
	if err != nil {
		t.Fatal(err)
	}
	head, err := sdk.Head()
	if err != nil {
		t.Fatal(err)
	}
	counter, err := sdk.Counter(head.Hash, pkh)
	if err != nil {
		t.Fatal(err)
	}
	contents := []gotezos.Contents{{
		Kind:         gotezos.REVEALOP,
		Source:       pkh,
		Fee:          gotezos.Int{big.NewInt(1000000)},
		Counter:      gotezos.Int{big.NewInt(int64(*counter + 1))},
		GasLimit:     gotezos.Int{big.NewInt(100000)},
		StorageLimit: gotezos.Int{big.NewInt(100000)},
		Amount:       gotezos.Int{},
		Phk:          pubKey,
	}}
	operationBytes, err := gotezos.ForgeOperation(head.Hash, contents...)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(*operationBytes)
	signature, err := wallet.SignOperation(*operationBytes)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(signature)
}
```
the result is:
```
panic: ed25519: bad private key length: 98 [recovered]
	panic: ed25519: bad private key length: 98

goroutine 19 [running]:
testing.tRunner.func1(0xc0000ece00)
	F:/Go/src/testing/testing.go:830 +0x399
panic(0x72e460, 0xc0003de330)
	F:/Go/src/runtime/panic.go:522 +0x1c3
golang.org/x/crypto/ed25519.Sign(0xc000010700, 0x62, 0x70, 0xc0001b2c60, 0x20, 0x20, 0x20, 0x70, 0x0)
	F:/code/pkg/mod/golang.org/x/crypto@v0.0.0-20200115085410-6d4e4cb37c7d/ed25519/ed25519.go:132 +0x575
```

After ```wallet, err := gotezos.ImportWallet(pkh, pubKey,"edskRhT17Wmv2gbRG8fh66kCM3pQ3xeNuv7Bn5vKJdEVJAoDiEdVf6zok1EPXrDEmDjxtGEGcCQaTs13vstjmjjKDw7A5twsCh")```, the wallet.Kp.PrivKey length is 98.

**Comment by qiluge** [comment]
I found you merged sign feature and test it. Are there some incompitable with existed feature? And please pay some attention to my other issue https://github.com/goat-systems/go-tezos/issues/130.
Thx!

**Comment by DefinitelyNotAGoat** [comment]
I ran into this issue myself. It should be fixed with the latest release. As it stands this library is tagged alpha and could change frequently. I try not to make breaking changes, but some times they make sense during this stage.

Also I added individual functions to the supported operations. It might be easier for you to now use the ForgeRevealOperation function.
